### PR TITLE
RELATED: FET-564 Sonar config

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by pbenes** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Review by ivanmjartan — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-merge-compliance-check/13/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-fossa-scanning-zuul-el7/9/ : FAILURE in 2m 05s (non-voting)

**Pull request merged**
