### PR TITLE
RELATED: SPACE-2111 Add NOTICE.txt file

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by xMort — APPROVED** [review]

**Comment by xMort** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=grunt-grizzly-gate-PR74

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-merge-compliance-check/19/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-sonarqube-scan-zuul-gate/5/ : SUCCESS in 53s
- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-fossa-scanning-zuul-el7/15/ : FAILURE in 41s (non-voting)

**Pull request merged**
