### PR TITLE
RELATED: FET-458 Get rid of minimist package with vulnerability

### PR DESCRIPTION
**Pull request by patrikbraborec**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by patrikbraborec** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by pbenes — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-merge-compliance-check/11/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-fossa-scanning-zuul-el7/7/ : SUCCESS in 1m 36s (non-voting)

**Pull request merged**
