### PR TITLE
RELATED: FET-564 Sonar config

### PR DESCRIPTION
**Pull request by ivanmjartan**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by pbenes** [comment]
extended check sonar

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-sonarqube-scan-zuul-el7/1/ : SUCCESS in 32s (non-voting)

**Comment by ivanmjartan** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=grunt-grizzly-check-extended-sonar-PR62

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=grunt-grizzly-check-extended-sonar-PR62

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-sonarqube-scan-zuul-el7/2/ : SUCCESS in 36s (non-voting)

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - No new bug found. Congratulation!

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=grunt-grizzly-gate-PR62

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-sonarqube-scan-zuul-el7/3/ : SUCCESS in 34s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-merge-compliance-check/14/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/grunt-grizzly-fossa-scanning-zuul-el7/10/ : FAILURE in 1m 54s (non-voting)

**Pull request merged**
